###服务启动端口号
server:
  port: 8183
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: shop-pay
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka,http://localhost:9093/eureka
    ###注册自己
    register-with-eureka: true
    ###从eureka上获取注册信息
    fetch-registry: true
