###服务端口号
server:
  port: 9090
###服务名称
spring:
  application:
    name: eureka-server
###eureka 基本信息配置
eureka:
  server:
    enable-self-preservation: false   #eureka自我保护机制，开发环境为false,线上环境强烈要求为true
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9090/eureka/
    ###因为自己是为注册中心，不需要自己注册自己，如果是要做eureka集群，則true
    register-with-eureka: true
    ###因为自己是为注册中心，不需要检索服务
    fetch-registry: true
